import Head from "next/head";

//Provide Data back-end (query.js)
import { useQuery } from "urql";

import { PRODUCT_QUERY } from "../lib/query";

//* Components
import Product from "../components/Product";


//Css
import { Gallery } from "../styles/GalleryCss";


export default function Home() {
  //Fecth products from strapi
  const [results] = useQuery({ query: PRODUCT_QUERY });
  // console.log(results);

  const { data, fetching, error } = results;

  //Check is the data coming in
  if (fetching) return <p>Loading...</p>;
  if (error) return <p>Oh no...{error.message}</p>;
  // console.log(data);

  const products = data.products.data;
  // console.log(products);

  return (
    <>
      <Head>
        <title>Styled Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Gallery>
        {products.map((product) => (
          <Product key={product.attributes.slug} product={product} />
        ))}

        </Gallery>
      </main>
    </>
  );
}
